name: "Lint Haskell"

on:
  workflow_call:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      # NOTE: There are some considerations for choosing the best fourmolu
      # version.
      #
      # 1. The glibc haskell-actions/fourmolu uses needs to match the runner.
      #    That isn't normally a problem, but a mismatch can lead to a message:
      #
      #        /lib64/libc.so.6: version `GLIBC_2.34' not found
      #
      #    and, confusingly, a misleading error message:
      #
      #        fourmolu detected unformatted files
      #
      #    If this happens, you may need to change the fourmolu version.
      #    A decent way to figure out what glibc CI has is to 'echo /lib64'
      #    and search the logs for 'libc-'.
      #
      # 2. It is generally a good idea to pick a version that uses the same
      #    ghc-lib-parser that corresponds to the GHC version. Hackage has this
      #    information: https://hackage.haskell.org/package/fourmolu
      #
      #    For GHC 9.4, this yields two major candidates:
      #
      #        - 0.10.1.0
      #        - 0.11.0.0
      #
      #    Ordinarily you might as well take the latest, but in this case there
      #    is a reason to favor 0.10: 0.11 introduces the ormolu-0.5.3.0 change
      #    "Normalize parentheses around constraints" that formats e.g.
      #
      #        HasCallStack => foo
      #
      #    as
      #
      #        (HasCallStack) => foo
      #
      #     The only problem with this is it runs up against the hlint rule
      #     "redundant bracket", thus there is a conflict.
      #
      #    There are three solutions:
      #
      #    1. Configure hlint to ignore "redundant bracket" in all repos where
      #       this is a problem.
      #    2. Upgrade fourmolu to 0.12+ and set its new
      #       'single-constraint-parens' option to false.
      #    3. Wait for hlint 3.6 (GHC 9.6), which fixes "redundant bracket"
      #       so that it doesn't fire in these instances.
      #
      #    In any case, fourmolu and hlint are no longer in conflict.
      #
      #    The solution requiring the least (i.e zero) work is to simply use
      #    fourmolu 0.10.1.0 for now. Once we upgrade to GHC 9.6+, both
      #    fourmolu and hlint can be upgraded, and this will not be a problem.
      #
      #    See https://github.com/tweag/ormolu/issues/1003 for details.

      - uses: haskell-actions/run-fourmolu@v9
        with:
          version: "0.10.1.0"

      - uses: haskell/actions/hlint-setup@v2
        with:
          version: "3.5"

      - uses: haskell/actions/hlint-run@v2
        with:
          path: "."
          fail-on: suggestion