name: "Lint Haskell"

on:
  workflow_call:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      # NOTE: There are some considerations for choosing the best fourmolu
      # version.
      #
      # 1. The glibc haskell-actions/fourmolu uses needs to match the runner.
      #    That isn't normally a problem, but a mismatch can lead to a message:
      #
      #        /lib64/libc.so.6: version `GLIBC_2.34' not found
      #
      #    and, confusingly, a misleading error message:
      #
      #        fourmolu detected unformatted files
      #
      #    If this happens, you may need to change the fourmolu version.
      #    A decent way to figure out what glibc CI has is to 'echo /lib64'
      #    and search the logs for 'libc-'.
      #
      # 2. It is generally a good idea to pick a version that uses the same
      #    ghc-lib-parser that corresponds to the GHC version. Hackage has this
      #    information: https://hackage.haskell.org/package/fourmolu
      #
      #    For GHC 9.6, this yields:
      #
      #        - 0.14.0.0


      - uses: haskell-actions/run-fourmolu@v9
        with:
          version: "0.14.0.0"

      - uses: haskell-actions/hlint-setup@v2
        with:
          version: "3.6"

      - uses: haskell-actions/hlint-run@v2
        with:
          path: "."
          fail-on: suggestion
