name: "Check Python"

on:
  workflow_call:
    inputs:
      pydocstyleMustPass:
        description: "If set to true, pydocstyle must pass"
        default: true
        type: boolean
      typecheckMustPass:
        description: "If set to true, type checking must pass"
        default: true
        type: boolean
      lintingMustPass:
        description: "If set to true, linting must pass"
        default: true
        type: boolean
      testsMustPass:
        description: "If set to true, testing must pass"
        default: true
        type: boolean
      pythonVersion:
        description: "Supply Python version for workflow"
        default: "3.9"
        type: string

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.BUILD_SSH_KEY }}

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.pythonVersion }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Check black formatting
        run: poetry run black . --check --diff

      - name: Check isort formatting
        run: poetry run isort . --check --diff

      - name: Check pydocstyle
        if: ${{ inputs.pydocstyleMustPass }}
        run: poetry run pydocstyle .

      - name: Check types
        if: ${{ inputs.typecheckMustPass }}
        run: poetry run mypy .

      - name: Linting
        if: ${{ inputs.lintingMustPass }}
        # Refernce: https://stackoverflow.com/a/63044665/8175935
        run: poetry run pylint $(git ls-files '*.py')

      - name: Run tests
        if: ${{ inputs.testsMustPass }}
        run: poetry run pytest
