name: Trigger Package + Upload
on:
  workflow_call:
    inputs:
      actor:
        required: true
        type: string

jobs:
  trigger:
    name: Trigger Package + Upload
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{ github.event.inputs.actor }}
      GH_TOKEN: ${{ secrets.PULL_TOKEN }}
    steps:
      - name: Trigger Package + Upload
        run: |
          gh workflow run --repo daiseeai/package.everything \
          -f actor=$ACTOR \
          packaging+upload.yaml
