name: Trigger Package + Upload
on:
  workflow_call:
    inputs:
      actor:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      actor:
        required: true
        type: string

jobs:
  trigger:
  runs-on: ubuntu-latest
  env:
    ACTOR: ${{ github.event.inputs.actor }}
  steps:
    - name: Trigger Package + Upload
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PULL_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/daiseeai/package.everything/actions/workflows/packaging+upload.yaml/dispatches \
          -d '{"ref":"main","inputs":{"actor":"'$ACTOR'""}}'
